#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-ttp
Version  : 0.8.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/3e/d3/1b1a58e725541f7f55b3fea379f594fb9cd849ff4ca73ec2f758fe523a9a/ttp-0.8.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/3e/d3/1b1a58e725541f7f55b3fea379f594fb9cd849ff4ca73ec2f758fe523a9a/ttp-0.8.1.tar.gz
Summary  : Template Text Parser
Group    : Development/Tools
License  : MIT
Requires: pypi-ttp-bin = %{version}-%{release}
Requires: pypi-ttp-license = %{version}-%{release}
Requires: pypi-ttp-python = %{version}-%{release}
Requires: pypi-ttp-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
[![Downloads](https://pepy.tech/badge/ttp)](https://pepy.tech/project/ttp)
[![PyPI versions](https://img.shields.io/pypi/pyversions/ttp.svg)](https://pypi.python.org/pypi/ttp/)
[![Documentation status](https://readthedocs.org/projects/ttp/badge/?version=latest)](http://ttp.readthedocs.io/?badge=latest)

%package bin
Summary: bin components for the pypi-ttp package.
Group: Binaries
Requires: pypi-ttp-license = %{version}-%{release}

%description bin
bin components for the pypi-ttp package.


%package license
Summary: license components for the pypi-ttp package.
Group: Default

%description license
license components for the pypi-ttp package.


%package python
Summary: python components for the pypi-ttp package.
Group: Default
Requires: pypi-ttp-python3 = %{version}-%{release}

%description python
python components for the pypi-ttp package.


%package python3
Summary: python3 components for the pypi-ttp package.
Group: Default
Requires: python3-core
Provides: pypi(ttp)

%description python3
python3 components for the pypi-ttp package.


%prep
%setup -q -n ttp-0.8.1
cd %{_builddir}/ttp-0.8.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639059337
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-ttp
cp %{_builddir}/ttp-0.8.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-ttp/2c3e3c541a2eb201039ade8d4d3f9c4da3af89ac
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)
/usr/LICENSE

%files bin
%defattr(-,root,root,-)
/usr/bin/ttp

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-ttp/2c3e3c541a2eb201039ade8d4d3f9c4da3af89ac

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
