#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-ttp
Version  : 0.9.1
Release  : 8
URL      : https://files.pythonhosted.org/packages/4d/27/e18b7a96e054112029085eb8527185138ca68f0cd3b5b0c6e67c3d34a0a0/ttp-0.9.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/4d/27/e18b7a96e054112029085eb8527185138ca68f0cd3b5b0c6e67c3d34a0a0/ttp-0.9.1.tar.gz
Summary  : Template Text Parser
Group    : Development/Tools
License  : MIT
Requires: pypi-ttp-bin = %{version}-%{release}
Requires: pypi-ttp-license = %{version}-%{release}
Requires: pypi-ttp-python = %{version}-%{release}
Requires: pypi-ttp-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry_core)

%description
[![Downloads](https://pepy.tech/badge/ttp)](https://pepy.tech/project/ttp)
[![PyPI versions](https://img.shields.io/pypi/pyversions/ttp.svg)](https://pypi.python.org/pypi/ttp/)
[![Documentation status](https://readthedocs.org/projects/ttp/badge/?version=latest)](http://ttp.readthedocs.io/?badge=latest)

%package bin
Summary: bin components for the pypi-ttp package.
Group: Binaries
Requires: pypi-ttp-license = %{version}-%{release}

%description bin
bin components for the pypi-ttp package.


%package license
Summary: license components for the pypi-ttp package.
Group: Default

%description license
license components for the pypi-ttp package.


%package python
Summary: python components for the pypi-ttp package.
Group: Default
Requires: pypi-ttp-python3 = %{version}-%{release}

%description python
python components for the pypi-ttp package.


%package python3
Summary: python3 components for the pypi-ttp package.
Group: Default
Requires: python3-core
Provides: pypi(ttp)

%description python3
python3 components for the pypi-ttp package.


%prep
%setup -q -n ttp-0.9.1
cd %{_builddir}/ttp-0.9.1
pushd ..
cp -a ttp-0.9.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1657556207
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-ttp
cp %{_builddir}/ttp-0.9.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-ttp/2c3e3c541a2eb201039ade8d4d3f9c4da3af89ac
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ttp

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-ttp/2c3e3c541a2eb201039ade8d4d3f9c4da3af89ac

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
